# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ConfigureRepoFilesystemLocations.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VirtualMachineBuilder(object):
    def setupUi(self, VirtualMachineBuilder):
        VirtualMachineBuilder.setObjectName("VirtualMachineBuilder")
        VirtualMachineBuilder.resize(672, 397)
        self.gridLayout = QtWidgets.QGridLayout(VirtualMachineBuilder)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(VirtualMachineBuilder)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.leMacos = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leMacos.setObjectName("leMacos")
        self.gridLayout.addWidget(self.leMacos, 2, 1, 1, 1)
        self.macosBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.macosBrowse.setObjectName("macosBrowse")
        self.gridLayout.addWidget(self.macosBrowse, 2, 2, 1, 1)
        self.leCentos = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leCentos.setObjectName("leCentos")
        self.gridLayout.addWidget(self.leCentos, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.centosBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.centosBrowse.setObjectName("centosBrowse")
        self.gridLayout.addWidget(self.centosBrowse, 3, 2, 1, 1)
        self.leUbuntu = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leUbuntu.setObjectName("leUbuntu")
        self.gridLayout.addWidget(self.leUbuntu, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.ubuntuBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.ubuntuBrowse.setObjectName("ubuntuBrowse")
        self.gridLayout.addWidget(self.ubuntuBrowse, 4, 2, 1, 1)
        self.leDebian = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leDebian.setObjectName("leDebian")
        self.gridLayout.addWidget(self.leDebian, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.debianBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.debianBrowse.setObjectName("debianBrowse")
        self.gridLayout.addWidget(self.debianBrowse, 5, 2, 1, 1)
        self.leFedora = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leFedora.setObjectName("leFedora")
        self.gridLayout.addWidget(self.leFedora, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.fedoraBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.fedoraBrowse.setObjectName("fedoraBrowse")
        self.gridLayout.addWidget(self.fedoraBrowse, 6, 2, 1, 1)
        self.leBsd = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leBsd.setObjectName("leBsd")
        self.gridLayout.addWidget(self.leBsd, 8, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.bsdBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.bsdBrowse.setObjectName("bsdBrowse")
        self.gridLayout.addWidget(self.bsdBrowse, 8, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.leOracle = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leOracle.setObjectName("leOracle")
        self.gridLayout.addWidget(self.leOracle, 7, 1, 1, 1)
        self.oracleBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.oracleBrowse.setObjectName("oracleBrowse")
        self.gridLayout.addWidget(self.oracleBrowse, 7, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(VirtualMachineBuilder)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(VirtualMachineBuilder)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.leWindows = QtWidgets.QLineEdit(VirtualMachineBuilder)
        self.leWindows.setObjectName("leWindows")
        self.gridLayout.addWidget(self.leWindows, 9, 1, 1, 1)
        self.windowsBrowse = QtWidgets.QPushButton(VirtualMachineBuilder)
        self.windowsBrowse.setObjectName("windowsBrowse")
        self.gridLayout.addWidget(self.windowsBrowse, 9, 2, 1, 1)

        self.retranslateUi(VirtualMachineBuilder)
        QtCore.QMetaObject.connectSlotsByName(VirtualMachineBuilder)

    def retranslateUi(self, VirtualMachineBuilder):
        _translate = QtCore.QCoreApplication.translate
        VirtualMachineBuilder.setWindowTitle(_translate("VirtualMachineBuilder", "Virtual Machine Builder"))
        self.label_11.setText(_translate("VirtualMachineBuilder", "<html><head/><body><p>Configure Repo Locations (must already exist on the system)</p></body></html>"))
        self.label.setText(_translate("VirtualMachineBuilder", "Boxcutter Git repo location on the local Filesystem"))
        self.label_3.setText(_translate("VirtualMachineBuilder", "macOS"))
        self.macosBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_4.setText(_translate("VirtualMachineBuilder", "centos"))
        self.centosBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_5.setText(_translate("VirtualMachineBuilder", "ubuntu"))
        self.ubuntuBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_6.setText(_translate("VirtualMachineBuilder", "debian"))
        self.debianBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_7.setText(_translate("VirtualMachineBuilder", "fedora"))
        self.fedoraBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_8.setText(_translate("VirtualMachineBuilder", "bsd"))
        self.bsdBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_9.setText(_translate("VirtualMachineBuilder", "oracle"))
        self.oracleBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))
        self.label_10.setText(_translate("VirtualMachineBuilder", "windows"))
        self.windowsBrowse.setText(_translate("VirtualMachineBuilder", "Browse"))

