# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VirtualMachineSettings2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 272)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.leVmName = QtWidgets.QLineEdit(Dialog)
        self.leVmName.setObjectName("leVmName")
        self.gridLayout.addWidget(self.leVmName, 2, 1, 1, 1)
        self.leComment = QtWidgets.QLineEdit(Dialog)
        self.leComment.setObjectName("leComment")
        self.gridLayout.addWidget(self.leComment, 1, 1, 1, 1)
        self.rbFalse = QtWidgets.QRadioButton(Dialog)
        self.rbFalse.setObjectName("rbFalse")
        self.gridLayout.addWidget(self.rbFalse, 4, 1, 1, 1)
        self.leDiskSize = QtWidgets.QLineEdit(Dialog)
        self.leDiskSize.setObjectName("leDiskSize")
        self.gridLayout.addWidget(self.leDiskSize, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.rbTrue = QtWidgets.QRadioButton(Dialog)
        self.rbTrue.setObjectName("rbTrue")
        self.gridLayout.addWidget(self.rbTrue, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.leMemory = QtWidgets.QLineEdit(Dialog)
        self.leMemory.setObjectName("leMemory")
        self.gridLayout.addWidget(self.leMemory, 6, 1, 1, 1)
        self.leCpuCount = QtWidgets.QLineEdit(Dialog)
        self.leCpuCount.setObjectName("leCpuCount")
        self.gridLayout.addWidget(self.leCpuCount, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 2, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 3, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 2, 1, 1)
        self.acquireSourceComboBox = QtWidgets.QComboBox(Dialog)
        self.acquireSourceComboBox.setObjectName("acquireSourceComboBox")
        self.gridLayout.addWidget(self.acquireSourceComboBox, 5, 2, 1, 1)
        self.pbAcquireSource = QtWidgets.QPushButton(Dialog)
        self.pbAcquireSource.setObjectName("pbAcquireSource")
        self.gridLayout.addWidget(self.pbAcquireSource, 6, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Virtual Machine Builder"))
        self.label.setText(_translate("Dialog", "Comment"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>Virtual Machine Settings</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "VM Name"))
        self.label_3.setText(_translate("Dialog", "Desktop"))
        self.rbFalse.setText(_translate("Dialog", "False"))
        self.label_4.setText(_translate("Dialog", "CPUs"))
        self.rbTrue.setText(_translate("Dialog", "True"))
        self.label_5.setText(_translate("Dialog", "Disk Size"))
        self.label_13.setText(_translate("Dialog", "Memory Size"))
        self.radioButton.setText(_translate("Dialog", "VmWare Guest"))
        self.radioButton_2.setText(_translate("Dialog", "Parallels Guest"))
        self.radioButton_3.setText(_translate("Dialog", "Virtualbox Guest"))
        self.checkBox.setText(_translate("Dialog", "Vagrant Box"))
        self.pbAcquireSource.setText(_translate("Dialog", "Acquire macOS Source Image"))

